initial: support for linux, with Linux related scripts/binary for arch on nabu
initially Includes scripts from extracted recovery image
sourced from - https://github.com/nabu-alarm/installation-guide/releases/tag/files

diff --git a/recovery/root/system/bin/common b/recovery/root/system/bin/common
--- a/recovery/root/system/bin/common
+++ b/recovery/root/system/bin/common
@@ -1,50 +1,167 @@
 #!/sbin/bash
-win=/dev/block/platform/soc/1d84000.ufshc/sda32
-esp=/dev/block/platform/soc/1d84000.ufshc/sda31
-
-stockpart(){
-sgdisk --clear --load-backup=/system/bin/stock_gpt /dev/block/sda
+set -e
+[ -v SCRIPTS_DEBUG ] && set -x
+base=/dev/block/by-name
+linux=/dev/block/sda32
+esp=/dev/block/sda31
+userdata=/dev/block/sda33
+metadata=/dev/block/sda19
+removeparts() {
+	for i in $(seq 31 40); do
+		if [ -e "/dev/block/sda$i" ]; then
+			parted -s /dev/block/sda rm "$i" 2>/dev/null
+		fi
+	done
 }
 
-formatwinesp(){
-mkfs.fat -F32 -s1 $esp -n ESPNABU
-mkfs.ntfs -f $win -L WINNABU
+formatlinuxesp() {
+	mkfs.fat -F32 -s1 "$esp" -n ESPNABU
+	mke2fs -t ext4 -F "$linux"
 }
 
-formatdata(){
-make_f2fs -f -g android /dev/block/sda31
-mke2fs -t ext4 -F /dev/block/sda19
+formatdata() {
+	if [ -e "$base/userdata" ]; then
+		make_f2fs -f -g android "$base/userdata"
+	else
+		make_f2fs -f -g android "$userdata"
+	fi
+	if [ -e "$base/metadata" ]; then
+		mke2fs -t ext4 -F "$base/metadata"
+	else
+		mke2fs -t ext4 -F "$metadata"
+	fi
 }
 
-formatwindata(){
-make_f2fs -f -g android /dev/block/sda33
-mke2fs -t ext4 -F /dev/block/sda19
+formatdatarestore() {
+	if [ -e "$base/userdata" ]; then
+		make_f2fs -f -g android "$base/userdata"
+	else
+		make_f2fs -f -g android "/dev/block/sda31"
+	fi
+	if [ -e "$base/metadata" ]; then
+		mke2fs -t ext4 -F "$base/metadata"
+	else
+		mke2fs -t ext4 -F "$metadata"
+	fi
 }
 
-restore(){
-stockpart
-parted -s /dev/block/sda resizepart 31 100%
-sync
-formatdata
+restore() {
+	removeparts
+	parted -s /dev/block/sda mkpart userdata ext4 10872MB 100%
+	sgdisk --resize-table 32 /dev/block/sda
+	sync
+	formatdatarestore
 }
 
-fixgpt() {
-  for dev in /dev/block/sd{a..f}; do gdisk "$dev" <<< $'x\nj\n\nk\n\nw\nY\n'; done
+umountm() {
+	local part
+	local args
+	local real_part
+	part="${1:-}"
+	args=()
+	if [ -n "$part" ]; then
+		if [ $# -gt 0 ]; then
+			shift
+			args=("$@")
+		fi
+		if [ -L "$part" ]; then
+			real_part=$(readlink -f "$part")
+		else
+			real_part="$part"
+		fi
+		if grep -q "$real_part" /proc/mounts; then
+			umount "$part" "${args[@]}"
+		fi
+	fi
 }
 
-[ -e /config/usb_gadget/g1/configs/b.1/mass_storage.0 ] && echo "msc is enabled! aborting..." && echo "reboot and run the script again." && exit 1
+attach_chroot() {
+	mkdir /mnt/linux/root -p
+	mount /dev/block/by-name/linux /mnt/linux/root
+	mount /dev/block/by-name/esp /mnt/linux/root/boot/efi
+	mount -t proc proc /mnt/linux/root/proc
+	mount -t sysfs sysfs /mnt/linux/root/sys
+	mount -o bind /dev /mnt/linux/root/dev
+	mount -o bind /dev/pts /mnt/linux/root/dev/pts
+}
 
-if getprop sys.usb.config | grep -q "mtp"; then
-    echo " "
-    echo "run the script again!"
-    sleep 1
-    setprop sys.usb.config adb
-    rm /config/usb_gadget/g1/configs/b.1/f*
-    exit
+detach_chroot() {
+	umountm /mnt/linux/root/dev/pts
+	umountm /mnt/linux/root/dev
+	umountm /mnt/linux/root/sys
+	umountm /mnt/linux/root/proc
+	umountm /mnt/linux/root/boot/efi
+	umountm /mnt/linux/root
+}
+
+if [ "${ignoreweirdness:-}" != true ]; then
+	for i in 1 2 3 4; do
+		if [ ! -e /dev/block/platform/soc/1d84000.ufshc/by-name/bk0$i ]; then
+			echo "this script will NOT work with weird partition layouts! please restore the partition table by flashing gpt_both0 in fastboot!"
+			exit 1
+		fi
+	done
 fi
 
-max=$(( $(blockdev --getsize64 /dev/block/sda) / 1000000 ))
+if [ -e /config/usb_gadget/g1/configs/b.1/mass_storage.0 ]; then
+	echo "msc is enabled! aborting..."
+	echo "reboot and run the script again."
+	exit 1
+fi
 
-for i in sdcard data; do umount -lf /$i 2>/dev/null; done
-dmsetup remove -f userdata 2>/dev/null
-for i in esp win linux firmware mnt userdata metadata misc vendor; do umount -lf /dev/block/platform/soc/1d84000.ufshc/by-name/$i 2> /dev/null; done
+if getprop sys.usb.config | grep -q "mtp"; then
+	echo "run the script again!"
+	sleep 1
+	setprop sys.usb.config adb
+	rm /config/usb_gadget/g1/configs/b.1/f*
+	exit
+fi
+
+blocksize=$(blockdev --getsize64 /dev/block/sda)
+if [[ $blocksize =~ ^125[0-9]{9}$ ]]; then
+	max=125586
+elif [[ $blocksize =~ ^253[0-9]{9}$ ]]; then
+	max=253546
+elif [[ $blocksize =~ ^509[0-9]{9}$ ]]; then
+	max=509465
+elif [[ $blocksize =~ ^1021[0-9]{9}$ ]]; then
+	max=1021329
+else
+	echo "is this nabu?"
+	exit 1
+fi
+export max
+
+for i in sdcard data; do
+	if mountpoint -q /$i; then
+		twrp unmount /$i >/dev/null 2>&1
+	fi
+done
+
+for i in esp win firmware mnt userdata metadata misc vendor linux; do
+	umountm "$base/$i" 2>/dev/null
+done
+if dmsetup status | grep userdata -q; then
+	dmsetup remove userdata 2>/dev/null
+fi
+
+detach_chroot
+
+if [ "${ignoreweirdness:-}" != true ]; then
+
+	if weirdparts=$(find /dev/block -type b | grep -E '/sda(3[4-9]|[4-9][0-9])$'); then
+		echo -n "In order to use this script, your partition table has to be restored to the stock variant. ALL DATA WILL BE LOST. Continue (y/n)? "
+		read -r yn
+		[[ $yn =~ ^[Yy].*$ ]] || {
+			echo "Can't proceed without restoring the table."
+			exit 1
+		}
+		echo "Restoring the stock partition layout now..."
+		for i in $weirdparts; do
+			f="${i:14}"
+			parted -s /dev/block/sda rm "$f" 2>/dev/null
+		done
+		restore
+		exit 0
+	fi
+fi
diff --git a/recovery/root/system/bin/partition b/recovery/root/system/bin/partition
--- a/recovery/root/system/bin/partition
+++ b/recovery/root/system/bin/partition
@@ -1,62 +1,36 @@
 #!/sbin/bash
-. common
+if [[ -n $1 ]]; then
+	. common
+	linmax=$(echo "($max - 11222 - 8000)/1000" | bc)
+	echo "min size is 30, max size is less then $linmax"
 
-RESERVED_START=11222
-RESERVED_END=7000
+	if ! [[ -z $2 && $1 =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "30 < $1 && $1 < $linmax" | bc) == 1 ]]; then
+		echo "invalid argument!"
+		exit 1
+	fi
 
-usable_mb=$((max - RESERVED_START - RESERVED_END))
-winmax=$((usable_mb / 1000))
-input="${1-}"
-size=$(echo "$input" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]' | sed 's/gb$//;s/[^0-9.]//g')
-if [[ -z "$input" ]]; then
-    winend=$(((max + RESERVED_START) / 2))
+	echo "$(echo "scale=2; $1*1000/1024" | bc)GiB of space will be given to the main linux parition"
+	linend=$(echo "$1*1000 + 11222" | bc)
+	echo "userdata will get $(echo "scale=2;($max-$linend)/1024" | bc)GiB of space"
+	echo -n "does that sound good (y/n)? "
+	read -r yn
+	[[ $yn =~ ^[Yy].*$ ]] || {
+		echo "rethink things carefully and, eventually, you'll come to a conclusion."
+		exit 1
+	}
 else
-    if ! [[ "$size" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
-        echo "Invalid input. Please enter a number (e.g., 60GB)" >&2
-        exit 1
-    fi
-    size_int=$(echo "$size" | cut -d'.' -f1)
-    if (( size_int < 25 || size_int > winmax )); then
-        echo "Invalid size! Min: 25GB, Max: ${winmax}GB" >&2
-        exit 1
-    fi
-    winend=$(echo "$size * 1000" | bc)
-    winend=$(printf "%.0f" "$winend")
-    winend=$(( (winend + 1023) / 1024 * 1024 ))
-    winend=$((winend + RESERVED_START))
+	echo "Usage: parition [linux partition size in GiB]"
+	exit 1
 fi
-windows_gb=$(echo "scale=2; ($winend - $RESERVED_START) / 1000" | bc)
-userdata_gb=$(echo "scale=2; ($max - $winend) / 1000" | bc)
-echo ""
-echo "Windows Partition: $windows_gb GB"
-echo "Android Partition: $userdata_gb GB"
-while true; do
-  echo ""
-  echo -n "Does this look good? (y/n): "
-  read yn
-  case "$yn" in
-    [Yy]* ) break ;;
-    [Nn]* ) echo "Operation cancelled"; exit 1 ;;
-    * ) echo "Please enter (yes/y/Y or no/n/N)." ;;
-  esac
-done
-echo ""
-echo "Proceeding with Windows partitioning..."
-echo ""
-disk=/dev/block/sda
-stockpart
-sgdisk --resize-table 64 "$disk"
-parted -s "$disk" \
-  rm 31 \
-  mkpart esp fat32 10872MB 11222MB \
-  mkpart win ntfs 11222MB "${winend}MB" \
-  mkpart userdata ext4 "${winend}MB" 100% \
-  set 31 esp on
 
+removeparts
+sgdisk --resize-table 64 /dev/block/sda
+parted -s /dev/block/sda \
+	mkpart esp fat32 10872MB 11222MB \
+	mkpart linux ext4 11222MB "$linend" \
+	mkpart userdata ext4 "$linend" 100% \
+	set 31 esp on
 sync
-formatwindata
-formatwinesp
-fixgpt
-sync
-parted "$disk" p free
+formatlinuxesp
+formatdata
 echo "done!"
