Set Minimum windows partition size to 25GB in partition script

diff --git a/recovery/root/system/bin/partition b/recovery/root/system/bin/partition
--- a/recovery/root/system/bin/partition
+++ b/recovery/root/system/bin/partition
@@ -16,8 +16,8 @@ else
         exit 1
     fi
     size_int=$(echo "$size" | cut -d'.' -f1)
-    if (( size_int < 30 || size_int > winmax )); then
-        echo "Invalid size! Min: 30GB, Max: ${winmax}GB" >&2
+    if (( size_int < 25 || size_int > winmax )); then
+        echo "Invalid size! Min: 25GB, Max: ${winmax}GB" >&2
         exit 1
     fi
     winend=$(echo "$size * 1000" | bc)
