updated some scripts by @Kumar-Jy and add wintools page

diff --git a/recovery/root/system/bin/partition b/recovery/root/system/bin/partition
--- a/recovery/root/system/bin/partition
+++ b/recovery/root/system/bin/partition
@@ -1,25 +1,38 @@
 #!/sbin/bash
 . common
-if [[ -n $1 ]]; then
-winmax=$(echo "($max - 11222 - 8000)/1000" | bc)
-echo "min size is 30, max size is less then $winmax"
-! [[ -z $2 && $1 =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "30 < $1 && $1 < $winmax" | bc) == 1 ]] && echo "invalid argument!" && exit 1
-echo ""$(echo "scale=2; $1*1000/1024" | bc)"GiB of space will be given to the main windows parition"
-winend=$(echo "$1*1000 + 11222" | bc)
-echo "userdata will get "$(echo "scale=2;($max-$winend)/1024" | bc)"GiB of space"
-echo -n "does that sound good (y/n)? "
-read yn
-[[ $yn =~ ^[Yy].*$ ]] || { echo "rethink things carefully and, eventually, you'll come to a conclusion.";exit 1; }
-fi
+
+size=$(echo "${1-}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]' | sed 's/gb$//;s/[^0-9.]//g')
+winmax=$(echo "($max-11222-8000)/1000" | bc)
+winend=$([[ -z ${1-} ]] && echo "($max+11222)/2" | bc || {
+  if ! [[ $size =~ ^[0-9]+(\.[0-9]+)?$ ]] || (( $(echo "$size<=30 || $size>=$winmax" | bc) )); then
+    echo "Invalid size! Min:30GB, Max:<${winmax}GB" >&2; exit 1
+  fi
+  echo "$size*1000+11222"
+} | bc)
+winend=$(printf "%.0f" "$winend")
+winend=$(( (winend + 1023) / 1024 * 1024 ))  # Force 1MB alignment
+echo "Windows: $(echo "scale=2;($winend-11222)/1024" | bc)GiB"
+echo "Userdata: $(echo "scale=2;($max-$winend)/1024" | bc)GiB"
+echo -n "does this sound good (y/n)? "
+until read -p "Continue (y/n)? " yn && [[ $yn =~ ^([Yy]($|[Ee][Ss]?)|[Nn]($|[Oo]?))$ ]]; do
+  echo "Please answer y/n/yes/no"
+done
+[[ $yn =~ ^[Yy] ]] || { echo "Operation cancelled"; exit 1; }
+
+disk=/dev/block/sda
 removeparts
-sgdisk --resize-table 64 /dev/block/sda
-parted -s /dev/block/sda \
+sgdisk --resize-table 64 $disk
+parted -s $disk \
   mkpart esp fat32 10872MB 11222MB \
-  mkpart win ntfs 11222MB $winend \
-  mkpart userdata ext4 $winend 100% \
+  mkpart win ntfs 11222MB "${winend}MB" \
+  mkpart userdata ext4 "${winend}MB" 100% \
   set 31 esp on
-sync
+
+sync 
 formatwindata
 formatwinesp
 fixgpt
+sync
+parted $disk p
+
 echo "done!"
